tabs = false

[font]
size = 12
features = {"JetBrainsMono" = ["+cv02", "+cv03", "+cv04", "+cv05", "+cv06", "+cv07", "+cv08", "+cv10", "+cv11", "+cv12", "+cv14", "+cv15", "+cv16", "+cv17", "+cv18", "+cv19", "+cv20"], "FiraCode" = ["+cv01", "+cv02", "+zero", "+cv11", "+cv14", "+onum", "+cv16", "+cv29", "+cv31"], "VictorMono" = ["+ss01", "+ss04", "+ss06"], "Recursive Mn Lnr St" = ["-dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss08", "+ss10", "+ss11", "+ss12"], "Recursive Mn Csl St" = ["-dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss08", "+ss10", "+ss11", "+ss12"]}

[[font.normal]]
family = "Recursive Mn Lnr St"
style = "Medium"

[[font.bold]]
family = "Recursive Mn Lnr St"
style = "SemiBold"

[[font.italic]]
family = "Recursive Mn Csl St"
style = "Medium"

[[font.bold_italic]]
family = "Recursive Mn Csl St"
style = "SemiBold"
